### ISSUE TITLE
Create docker files to containerize the backend and frontend

### ISSUE THREAD

**Issue by braydenidzenga** [braydenidzenga/Brogram#25]
Create two separate docker files that build the backend and the frontend as two separate containers.

**Comment by DeathwingIN** [comment]
can u assign me to this issue

**Comment by vipul-dixit-2004** [comment]
Hello @braydenidzenga,
I will create 2 ```Dockerfile``` in each directory a directory and ```docker-compose.yml``` file in the root directory to build both the api and frontend with one command. i.e. ```docker-compose up --build```. 
Kindly assign me this issue.

**Comment by braydenidzenga** [comment]
@vipul-dixit-2004 I assigned this over to you.

**Comment by vipul-dixit-2004** [comment]
Thanks @braydenidzenga,
I have done a PR kindly check

**Comment by vipul-dixit-2004** [comment]
@braydenidzenga I have completed the frontend docker setup also. Kindly review my latest PR.
