### ISSUE TITLE
Introduce Auth Middleware for Token Verification

### ISSUE THREAD

**Issue by ardatosun** [braydenidzenga/Brogram#29]
### Description
Currently, token verification logic is duplicated across several controllers, such as `NewPost.js`, `DeletePost.js`, and `LikePost.js`. To enhance maintainability and reduce redundancy, we should extract this logic into a centralized authentication middleware. This will ensure consistency across the application and simplify future updates to the authentication mechanism.

### Tasks

1. **Create `authMiddleware.js`:**
   - Implement middleware to handle token verification, checking the `Authorization` header for a valid JWT.
   - Attach the decoded user object to the `req.user` object upon successful verification.
   - Return `401 Unauthorized` for invalid or missing tokens, and ensure proper error handling in case of token verification failure.

2. **Refactor Existing Routes:**
   - Update all routes to use `authMiddleware` except ones under `auth` folder

3. **Remove duplicated token verification code from controllers**

### Expected Outcome
- All token verification logic should be centralized in `authMiddleware`.
- API routes should function correctly with consistent authentication behavior and appropriate status codes for valid and invalid token scenarios.

**Comment by ardatosun** [comment]
@braydenidzenga could you assign this issue to me? I can open PR soon

**Comment by braydenidzenga** [comment]
@ardatosun I assigned this over to you
