### ISSUE TITLE
UI and Content updates

### ISSUE THREAD

**Issue by Prantaneel-Pegu** [braydenidzenga/Brogram#35]
Currently, the getting started page and dummy landing page is quite basic and lacking content. Plus there are some styling deficits, like no horizontal padding in dummy landing page etc. I request an admin to assign me with the task of updating and improving these pages and adding relevant content.

**Comment by Prantaneel-Pegu** [comment]
I would also work on breaking up the pages into smaller components, improving ease of working.

**Comment by braydenidzenga** [comment]
@Prantaneel-Pegu I have assigned this to you

**Comment by Prantaneel-Pegu** [comment]
Request you to add Hacktoberfest tag to this issue.
