### ISSUE TITLE
Terms of Service, Privacy Policy and Content Policy Implementation

### ISSUE THREAD

**Issue by Prantaneel-Pegu** [braydenidzenga/Brogram#36]
These are not yet implemented in the dummy home page. I would like to take the initiative to implement it. Of course, I'll only put sensible data in there.

**Comment by Prantaneel-Pegu** [comment]
Request you to add Hacktoberfest tag to this issue.

**Comment by Prantaneel-Pegu** [comment]
Assign this to me please.

**Comment by braydenidzenga** [comment]
@Prantaneel-Pegu Assigned this to you as well.
