### ISSUE TITLE
Dev Experience improvement + Navigation Bar update

### ISSUE THREAD

**Issue by Prantaneel-Pegu** [braydenidzenga/Brogram#39]
I propose two updates -

1. We add and configure prettier in this project, to normalize the project styles. After that, we'll be able to install the official prettier tailwind plugin, a highly recommended plugin normalizing tailwind styles order.
2. We add dark mode toggle button in Navigation Bar. Would look better. 

I would like to take the initiative to implement these updates. I would put some very sensible settings in the prettier config, and also optimize and style the navigation bar.

**Comment by braydenidzenga** [comment]
@Prantaneel-Pegu these are good ideas but before I assign this over to you, would you be able to fix the conflicts in your latest pr.

**Comment by Prantaneel-Pegu** [comment]
> @Prantaneel-Pegu these are good ideas but before I assign this over to you, would you be able to fix the conflicts in your latest pr.

Done

**Comment by braydenidzenga** [comment]
@Prantaneel-Pegu I'm assigning this over to you
