### ISSUE TITLE
Make Home page default + Correct Eslint errors and warnings

### ISSUE THREAD

**Issue by Prantaneel-Pegu** [braydenidzenga/Brogram#42]
I propose these updates:

1. We make home page the default page. I.e. when people visit "/", the dummy home page is served. The getting-started page will remain in its original path, and a link to it will be added in the home page.
2.  As of now, there are multiple eslint errors and warnings in many files. You can find a warning or error in almost every file you open. I want to correct these warnings and errors, to the best of my ability. I will be focusing mainly on the "frontend" directory.

I want to implement these updates.

Please assign this issue to me.

**Comment by braydenidzenga** [comment]
@Prantaneel-Pegu I have assigned this to you
